Create course API and component.
Sunyam-Lexicon-2024/lms pull request #14
Opened 2024-06-28 14:36 UTC by hellomynameislinda

2024-06-28 17:13 UTC, suny-am commented on LMS.Core/Models/CourseCreateModel.cs
> +    [MinLength(3, ErrorMessage = "The name must be at least 3 charactrs to be identifiable")]
Det ä bäst att ha alla valideringar samlade i Endpoint Validator för att inte sprida ut validerings-logiken på flera ställen.

2024-06-28 17:18 UTC, suny-am commented on LMS.Client/Components/Pages/Shared/CreateCourse.razor
> +                        <label for="startdate" class="form-label">Start date</label>
Det kunde vara bra att använda `EnableMinMax= "true"` här och begränsa de möjliga datumvalen till att inte gå tillbaka i tiden.

2024-06-28 17:19 UTC, suny-am commented on LMS.API/Features/Courses/CreateCourse/Validator.cs
> +        RuleFor(c => c.Name)
Kanske ett minimum-värde här med?

2024-07-01 08:53 UTC, hellomynameislinda commented on LMS.Core/Models/CourseCreateModel.cs
> +    [MinLength(3, ErrorMessage = "The name must be at least 3 charactrs to be identifiable")]
La till en minimilängd i Validator och tog bort all validering i modellen. Jag var inte osäker på om endpointens validering räckte, insåg att den inte verkade använda valideringen i modellen oavsett, men råkade lämna kvar den.

2024-07-01 08:56 UTC, hellomynameislinda commented on LMS.Client/Components/Pages/Shared/CreateCourse.razor
> +                ToastService.Notify(new(ToastType.Danger, $"Could not create activity'{CourseCreate.Name}'."));
Äsch, den var ju slarvig, jag ändrade variabeln men missade texten.

2024-07-01 09:01 UTC, hellomynameislinda commented on LMS.Client/Components/Pages/Shared/CreateCourse.razor
> +                        <label for="startdate" class="form-label">Start date</label>
Tänker du på raden under, InputDate-taggarna?
Ska kika på den. Men det ska inte gå att gå tillbaka i tiden som det är nu, då min sätts till dagens datum. Och valideringen sköter så att slutdatum inte kan ligga före startdatum. Eller missar jag nåt?

2024-07-01 09:02 UTC, hellomynameislinda commented on LMS.API/Features/Courses/CreateCourse/Validator.cs
> +        RuleFor(c => c.Name)
Fixat enligt översta kommentaren!

2024-07-01 09:10 UTC, hellomynameislinda commented on LMS.Client/Components/Pages/Shared/CreateCourse.razor
> +                        <label for="startdate" class="form-label">Start date</label>
Ah, nu ser jag. Du använder Blazor Bootstrap-komponenten för formuläret, och en funktion specifik för den, och jag använder den vanliga.
Är det bättre att byta tycker du?

2024-07-01 09:21 UTC, suny-am commented on LMS.Client/Components/Pages/Shared/CreateCourse.razor
> +                        <label for="startdate" class="form-label">Start date</label>
Jag tycker att det blir litet bättre från ett UX-perspektiv?

2024-07-01 09:34 UTC, hellomynameislinda commented on LMS.Client/Components/Pages/Shared/CreateCourse.razor
> +    private ApiErrorResponseModel? _errorResponse;
Nu är den inlagd.

Man skulle ju vilja ha snyggare svar egentligen, med fältrubrik istället för fältnamn, och att den inte ens försöker spara. Men good enough ;)

2024-07-01 10:39 UTC, suny-am requested changes
Ser bra ut!

Jag undrar om vi bör lägga till litet margin i huvud-containern i `MainLayout.razor`? Detta så att man kan se botten på allt innehåll som annat kan hamna under footer-elementet (märkte detta tex när man får ut felmeddelanden i validering på formulär inline i `TeacherHome.razor`)?


e.g


```html
<div class="container container-xl my-5">
```

2024-07-01 11:43 UTC, merged